
on: 
  workflow_dispatch:

# Allows external webhook trigger
  repository_dispatch:
    types: [terraform-plan-received]
      
jobs:
  wzi-cli-scan:
    name: "Wiz-cli IaC Scan"
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "."
      POLICY: "Default IaC policy"
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: extract repo and run name
      # example: "https://github.com/pruClement/terraform/actions/runs/13986347053/artifacts/2794018099"
      # run: echo '${{ github.event.client_payload.artifact_url }}'
        id: extract
        run : |
          echo ARTIFACT_URL='${{ github.event.client_payload.artifact_url }}'
          REPO_NAME=$(echo "$ARTIFACT_URL" | awk -F'/' '{print $4 "/" $5}')
          # Extract run ID
          RUN_ID=$(echo "$ARTIFACT_URL" | awk -F'/' '{print $8}')
          
          echo "Extracted repository: $REPO_NAME"
          echo "Extracted run ID: $RUN_ID"

          # Set outputs
          echo "repo_name=$REPO_NAME" >> $GITHUB_OUTPUT
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          
      - name: Checking
        run: |
          echo $REPO_NAME
          echo $RUN_ID

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: artifact
          github-token: ${{ secrets.PRUCLEMENT_PAT }}
          repository: ${{ steps.split.outputs.ORG_NAME }} + "/" + ${{ steps.split.outputs.REPO_NAME }}
          run-id: ${{ steps.split.outputs.RUN_ID }}

      - name: unzip
        run: "ls"

    # - name: Download Wiz CLI
    #   run: curl -o wizcli https://downloads.wiz.io/wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

    # - name: Authenticate to Wiz
    #   run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
    #   env:
    #     WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
    #     WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    # - name: Run wiz CLI IaC scan
    #   run: ./wizcli iac scan --path $SCAN_PATH --policy "$POLICY" --policy-hits-only
