
on: 
  workflow_dispatch:

# Allows external webhook trigger
  repository_dispatch:
    types: [terraform-plan-received]
      
jobs:
  wzi-cli-scan:
    name: "Wiz-cli IaC Scan"
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "."
      POLICY: "Default IaC policy"
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: artifact
          github-token: {{secrets.PRUCLEMENT_PAT}}
          repository: pruClement/terraform
          run-id: 13985737671
