on: 
  workflow_dispatch:
    inputs:
      file_content:
        description: "file content description"

# Allows external webhook trigger
  repository_dispatch:
      
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "test wiz cli"
