on: 
  workflow_dispatch:

# Allows external webhook trigger
  repository_dispatch:
    types: [terraform-plan-received]
      
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "test wiz cli"
        run: echo '${{ github.event.client_payload.tfplan }}'
