on: 
  workflow_dispatch:
    inputs:
      terraform_json

# Allows external webhook trigger
  repository_dispatch:
    types:
      - webhook
      
jobs:
  printInputs:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "test wiz cli"
        echo ${{ inputs.terraform_json }}
